<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto\NetWorkLimitReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.NetWorkLimitReply.NetWorkEntity</code>
 */
class NetWorkEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int32 auth_content = 2;</code>
     */
    private $auth_content = 0;
    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 3;</code>
     */
    private $nw_firm_id = 0;
    /**
     * Generated from protobuf field <code>int32 report_currency = 4;</code>
     */
    private $report_currency = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $auth_content
     *     @type int $nw_firm_id
     *     @type int $report_currency
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 auth_content = 2;</code>
     * @return int
     */
    public function getAuthContent()
    {
        return $this->auth_content;
    }

    /**
     * Generated from protobuf field <code>int32 auth_content = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthContent($var)
    {
        GPBUtil::checkInt32($var);
        $this->auth_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 3;</code>
     * @return int
     */
    public function getNwFirmId()
    {
        return $this->nw_firm_id;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNwFirmId($var)
    {
        GPBUtil::checkInt32($var);
        $this->nw_firm_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 report_currency = 4;</code>
     * @return int
     */
    public function getReportCurrency()
    {
        return $this->report_currency;
    }

    /**
     * Generated from protobuf field <code>int32 report_currency = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReportCurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->report_currency = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NetWorkEntity::class, \Proto\NetWorkLimitReply_NetWorkEntity::class);

