<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto\OnePlacementGroup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OnePlacementGroup.OnePlacementGroupConfig</code>
 */
class OnePlacementGroupConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 abtype = 1;</code>
     */
    private $abtype = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 traffic_variation = 3;</code>
     */
    private $traffic_variation = 0;
    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     */
    private $createTime = '';
    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     */
    private $updateTime = '';
    /**
     * Generated from protobuf field <code>int32 capHourSwitch = 7;</code>
     */
    private $capHourSwitch = 0;
    /**
     * Generated from protobuf field <code>int32 capHour = 8;</code>
     */
    private $capHour = 0;
    /**
     * Generated from protobuf field <code>int32 capDay_switch = 9;</code>
     */
    private $capDay_switch = 0;
    /**
     * Generated from protobuf field <code>int32 capDay = 10;</code>
     */
    private $capDay = 0;
    /**
     * Generated from protobuf field <code>int32 pacingSwitch = 11;</code>
     */
    private $pacingSwitch = 0;
    /**
     * Generated from protobuf field <code>int32 pacing = 12;</code>
     */
    private $pacing = 0;
    /**
     * Generated from protobuf field <code>int32 autoRefresh = 13;</code>
     */
    private $autoRefresh = 0;
    /**
     * Generated from protobuf field <code>int32 autoRefreshTime = 14;</code>
     */
    private $autoRefreshTime = 0;
    /**
     * Generated from protobuf field <code>int32 trafficGroupId = 15;</code>
     */
    private $trafficGroupId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $abtype
     *     @type string $name
     *     @type int $traffic_variation
     *     @type int $status
     *     @type string $createTime
     *     @type string $updateTime
     *     @type int $capHourSwitch
     *     @type int $capHour
     *     @type int $capDay_switch
     *     @type int $capDay
     *     @type int $pacingSwitch
     *     @type int $pacing
     *     @type int $autoRefresh
     *     @type int $autoRefreshTime
     *     @type int $trafficGroupId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 abtype = 1;</code>
     * @return int
     */
    public function getAbtype()
    {
        return $this->abtype;
    }

    /**
     * Generated from protobuf field <code>int32 abtype = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAbtype($var)
    {
        GPBUtil::checkInt32($var);
        $this->abtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_variation = 3;</code>
     * @return int
     */
    public function getTrafficVariation()
    {
        return $this->traffic_variation;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_variation = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTrafficVariation($var)
    {
        GPBUtil::checkInt32($var);
        $this->traffic_variation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->createTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->updateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capHourSwitch = 7;</code>
     * @return int
     */
    public function getCapHourSwitch()
    {
        return $this->capHourSwitch;
    }

    /**
     * Generated from protobuf field <code>int32 capHourSwitch = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHourSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->capHourSwitch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capHour = 8;</code>
     * @return int
     */
    public function getCapHour()
    {
        return $this->capHour;
    }

    /**
     * Generated from protobuf field <code>int32 capHour = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHour($var)
    {
        GPBUtil::checkInt32($var);
        $this->capHour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capDay_switch = 9;</code>
     * @return int
     */
    public function getCapDaySwitch()
    {
        return $this->capDay_switch;
    }

    /**
     * Generated from protobuf field <code>int32 capDay_switch = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDaySwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->capDay_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capDay = 10;</code>
     * @return int
     */
    public function getCapDay()
    {
        return $this->capDay;
    }

    /**
     * Generated from protobuf field <code>int32 capDay = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->capDay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacingSwitch = 11;</code>
     * @return int
     */
    public function getPacingSwitch()
    {
        return $this->pacingSwitch;
    }

    /**
     * Generated from protobuf field <code>int32 pacingSwitch = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPacingSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacingSwitch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 12;</code>
     * @return int
     */
    public function getPacing()
    {
        return $this->pacing;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPacing($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 autoRefresh = 13;</code>
     * @return int
     */
    public function getAutoRefresh()
    {
        return $this->autoRefresh;
    }

    /**
     * Generated from protobuf field <code>int32 autoRefresh = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setAutoRefresh($var)
    {
        GPBUtil::checkInt32($var);
        $this->autoRefresh = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 autoRefreshTime = 14;</code>
     * @return int
     */
    public function getAutoRefreshTime()
    {
        return $this->autoRefreshTime;
    }

    /**
     * Generated from protobuf field <code>int32 autoRefreshTime = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setAutoRefreshTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->autoRefreshTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 trafficGroupId = 15;</code>
     * @return int
     */
    public function getTrafficGroupId()
    {
        return $this->trafficGroupId;
    }

    /**
     * Generated from protobuf field <code>int32 trafficGroupId = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setTrafficGroupId($var)
    {
        GPBUtil::checkInt32($var);
        $this->trafficGroupId = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OnePlacementGroupConfig::class, \Proto\OnePlacementGroup_OnePlacementGroupConfig::class);

