<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto\UnitUpInfoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitUpInfoList.UnitUpInfo</code>
 */
class UnitUpInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string unit_name = 1;</code>
     */
    private $unit_name = '';
    /**
     * Generated from protobuf field <code>string placement_name = 2;</code>
     */
    private $placement_name = '';
    /**
     * Generated from protobuf field <code>string nwf_name = 3;</code>
     */
    private $nwf_name = '';
    /**
     * Generated from protobuf field <code>int32 nwf_id = 4;</code>
     */
    private $nwf_id = 0;
    /**
     * Generated from protobuf field <code>string remote_unit = 5;</code>
     */
    private $remote_unit = '';
    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>int32 placement_id = 7;</code>
     */
    private $placement_id = 0;
    /**
     * Generated from protobuf field <code>int32 unit_id = 8;</code>
     */
    private $unit_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $unit_name
     *     @type string $placement_name
     *     @type string $nwf_name
     *     @type int $nwf_id
     *     @type string $remote_unit
     *     @type int $status
     *     @type int $placement_id
     *     @type int $unit_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string unit_name = 1;</code>
     * @return string
     */
    public function getUnitName()
    {
        return $this->unit_name;
    }

    /**
     * Generated from protobuf field <code>string unit_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitName($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placement_name = 2;</code>
     * @return string
     */
    public function getPlacementName()
    {
        return $this->placement_name;
    }

    /**
     * Generated from protobuf field <code>string placement_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementName($var)
    {
        GPBUtil::checkString($var, True);
        $this->placement_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nwf_name = 3;</code>
     * @return string
     */
    public function getNwfName()
    {
        return $this->nwf_name;
    }

    /**
     * Generated from protobuf field <code>string nwf_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNwfName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nwf_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nwf_id = 4;</code>
     * @return int
     */
    public function getNwfId()
    {
        return $this->nwf_id;
    }

    /**
     * Generated from protobuf field <code>int32 nwf_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNwfId($var)
    {
        GPBUtil::checkInt32($var);
        $this->nwf_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remote_unit = 5;</code>
     * @return string
     */
    public function getRemoteUnit()
    {
        return $this->remote_unit;
    }

    /**
     * Generated from protobuf field <code>string remote_unit = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 placement_id = 7;</code>
     * @return int
     */
    public function getPlacementId()
    {
        return $this->placement_id;
    }

    /**
     * Generated from protobuf field <code>int32 placement_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkInt32($var);
        $this->placement_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 8;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UnitUpInfo::class, \Proto\UnitUpInfoList_UnitUpInfo::class);

