<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto\SegmentUnitList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SegmentUnitList.SegmentUnitEntity</code>
 */
class SegmentUnitEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 segment_id = 1;</code>
     */
    private $segment_id = 0;
    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     */
    private $unit_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $segment_id
     *     @type int $unit_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 segment_id = 1;</code>
     * @return int
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>int32 segment_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkInt32($var);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SegmentUnitEntity::class, \Proto\SegmentUnitList_SegmentUnitEntity::class);

