<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.CloseNetwork</code>
 */
class CloseNetwork extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 publisherId = 1;</code>
     */
    private $publisherId = 0;
    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 2;</code>
     */
    private $nw_firm_id = 0;
    /**
     * Generated from protobuf field <code>int32 admin_id = 3;</code>
     */
    private $admin_id = 0;
    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     */
    private $ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $publisherId
     *     @type int $nw_firm_id
     *     @type int $admin_id
     *     @type string $ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 1;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisherId;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 2;</code>
     * @return int
     */
    public function getNwFirmId()
    {
        return $this->nw_firm_id;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNwFirmId($var)
    {
        GPBUtil::checkInt32($var);
        $this->nw_firm_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 3;</code>
     * @return int
     */
    public function getAdminId()
    {
        return $this->admin_id;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAdminId($var)
    {
        GPBUtil::checkInt32($var);
        $this->admin_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

