<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GeoShort</code>
 */
class GeoShort extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string short = 1;</code>
     */
    private $short = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $short
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string short = 1;</code>
     * @return string
     */
    public function getShort()
    {
        return $this->short;
    }

    /**
     * Generated from protobuf field <code>string short = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->short = $var;

        return $this;
    }

}

