<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\NetWorkLimitReply\NetWorkEntity instead.
     * @deprecated
     */
    class NetWorkLimitReply_NetWorkEntity {}
}
class_exists(NetWorkLimitReply\NetWorkEntity::class);
@trigger_error('Proto\NetWorkLimitReply_NetWorkEntity is deprecated and will be removed in the next major release. Use Proto\NetWorkLimitReply\NetWorkEntity instead', E_USER_DEPRECATED);

