<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OnePlacementGroupData</code>
 */
class OnePlacementGroupData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit adSourceList = 1;</code>
     */
    private $adSourceList;
    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit freeAdSourceList = 2;</code>
     */
    private $freeAdSourceList;
    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segmentData = 3;</code>
     */
    private $segmentData = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $adSourceList
     *     @type \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $freeAdSourceList
     *     @type \Proto\SegmentGroup $segmentData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit adSourceList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdSourceList()
    {
        return $this->adSourceList;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit adSourceList = 1;</code>
     * @param \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdSourceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OnePlacementGroupSegmentUnit::class);
        $this->adSourceList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit freeAdSourceList = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFreeAdSourceList()
    {
        return $this->freeAdSourceList;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit freeAdSourceList = 2;</code>
     * @param \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFreeAdSourceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OnePlacementGroupSegmentUnit::class);
        $this->freeAdSourceList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segmentData = 3;</code>
     * @return \Proto\SegmentGroup
     */
    public function getSegmentData()
    {
        return $this->segmentData;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segmentData = 3;</code>
     * @param \Proto\SegmentGroup $var
     * @return $this
     */
    public function setSegmentData($var)
    {
        GPBUtil::checkMessage($var, \Proto\SegmentGroup::class);
        $this->segmentData = $var;

        return $this;
    }

}

