<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\OnePlacementGroup\OnePlacementGroupConfig instead.
     * @deprecated
     */
    class OnePlacementGroup_OnePlacementGroupConfig {}
}
class_exists(OnePlacementGroup\OnePlacementGroupConfig::class);
@trigger_error('Proto\OnePlacementGroup_OnePlacementGroupConfig is deprecated and will be removed in the next major release. Use Proto\OnePlacementGroup\OnePlacementGroupConfig instead', E_USER_DEPRECATED);

