<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OnePlacementGroupSegmentUnit</code>
 */
class OnePlacementGroupSegmentUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 mediation_connection_id = 1;</code>
     */
    private $mediation_connection_id = 0;
    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     */
    private $unit_id = 0;
    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     */
    private $ecpm_optimization_switch = 0;
    /**
     * Generated from protobuf field <code>int32 type = 4;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     */
    private $create_time = '';
    /**
     * Generated from protobuf field <code>string update_time = 6;</code>
     */
    private $update_time = '';
    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     */
    private $ecpm = '';
    /**
     * Generated from protobuf field <code>string name = 8;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string network_name = 9;</code>
     */
    private $network_name = '';
    /**
     * Generated from protobuf field <code>string remote_unit = 10;</code>
     */
    private $remote_unit = '';
    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 11;</code>
     */
    private $nw_firm_id = 0;
    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 12;</code>
     */
    private $cap_hour_switch = 0;
    /**
     * Generated from protobuf field <code>int32 cap_hour = 13;</code>
     */
    private $cap_hour = 0;
    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 14;</code>
     */
    private $cap_day_switch = 0;
    /**
     * Generated from protobuf field <code>int32 cap_day = 15;</code>
     */
    private $cap_day = 0;
    /**
     * Generated from protobuf field <code>int32 pacing_switch = 16;</code>
     */
    private $pacing_switch = 0;
    /**
     * Generated from protobuf field <code>int32 pacing = 17;</code>
     */
    private $pacing = 0;
    /**
     * Generated from protobuf field <code>string app_auth_content = 18;</code>
     */
    private $app_auth_content = '';
    /**
     * Generated from protobuf field <code>string real_ecpm = 19;</code>
     */
    private $real_ecpm = '';
    /**
     * Generated from protobuf field <code>int32 optimization_status = 20;</code>
     */
    private $optimization_status = 0;
    /**
     * Generated from protobuf field <code>int32 header_bidding_switch = 21;</code>
     */
    private $header_bidding_switch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mediation_connection_id
     *     @type int $unit_id
     *     @type int $ecpm_optimization_switch
     *     @type int $type
     *     @type string $create_time
     *     @type string $update_time
     *     @type string $ecpm
     *     @type string $name
     *     @type string $network_name
     *     @type string $remote_unit
     *     @type int $nw_firm_id
     *     @type int $cap_hour_switch
     *     @type int $cap_hour
     *     @type int $cap_day_switch
     *     @type int $cap_day
     *     @type int $pacing_switch
     *     @type int $pacing
     *     @type string $app_auth_content
     *     @type string $real_ecpm
     *     @type int $optimization_status
     *     @type int $header_bidding_switch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 mediation_connection_id = 1;</code>
     * @return int
     */
    public function getMediationConnectionId()
    {
        return $this->mediation_connection_id;
    }

    /**
     * Generated from protobuf field <code>int32 mediation_connection_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMediationConnectionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->mediation_connection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     * @return int
     */
    public function getEcpmOptimizationSwitch()
    {
        return $this->ecpm_optimization_switch;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEcpmOptimizationSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->ecpm_optimization_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string update_time = 6;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>string update_time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     * @return string
     */
    public function getEcpm()
    {
        return $this->ecpm;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEcpm($var)
    {
        GPBUtil::checkString($var, True);
        $this->ecpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network_name = 9;</code>
     * @return string
     */
    public function getNetworkName()
    {
        return $this->network_name;
    }

    /**
     * Generated from protobuf field <code>string network_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setNetworkName($var)
    {
        GPBUtil::checkString($var, True);
        $this->network_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remote_unit = 10;</code>
     * @return string
     */
    public function getRemoteUnit()
    {
        return $this->remote_unit;
    }

    /**
     * Generated from protobuf field <code>string remote_unit = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 11;</code>
     * @return int
     */
    public function getNwFirmId()
    {
        return $this->nw_firm_id;
    }

    /**
     * Generated from protobuf field <code>int32 nw_firm_id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setNwFirmId($var)
    {
        GPBUtil::checkInt32($var);
        $this->nw_firm_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 12;</code>
     * @return int
     */
    public function getCapHourSwitch()
    {
        return $this->cap_hour_switch;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHourSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_hour_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour = 13;</code>
     * @return int
     */
    public function getCapHour()
    {
        return $this->cap_hour;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHour($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_hour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 14;</code>
     * @return int
     */
    public function getCapDaySwitch()
    {
        return $this->cap_day_switch;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDaySwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_day_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day = 15;</code>
     * @return int
     */
    public function getCapDay()
    {
        return $this->cap_day;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacing_switch = 16;</code>
     * @return int
     */
    public function getPacingSwitch()
    {
        return $this->pacing_switch;
    }

    /**
     * Generated from protobuf field <code>int32 pacing_switch = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setPacingSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacing_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 17;</code>
     * @return int
     */
    public function getPacing()
    {
        return $this->pacing;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setPacing($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_auth_content = 18;</code>
     * @return string
     */
    public function getAppAuthContent()
    {
        return $this->app_auth_content;
    }

    /**
     * Generated from protobuf field <code>string app_auth_content = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setAppAuthContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_auth_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string real_ecpm = 19;</code>
     * @return string
     */
    public function getRealEcpm()
    {
        return $this->real_ecpm;
    }

    /**
     * Generated from protobuf field <code>string real_ecpm = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setRealEcpm($var)
    {
        GPBUtil::checkString($var, True);
        $this->real_ecpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 optimization_status = 20;</code>
     * @return int
     */
    public function getOptimizationStatus()
    {
        return $this->optimization_status;
    }

    /**
     * Generated from protobuf field <code>int32 optimization_status = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setOptimizationStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->optimization_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 header_bidding_switch = 21;</code>
     * @return int
     */
    public function getHeaderBiddingSwitch()
    {
        return $this->header_bidding_switch;
    }

    /**
     * Generated from protobuf field <code>int32 header_bidding_switch = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setHeaderBiddingSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->header_bidding_switch = $var;

        return $this;
    }

}

