<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OnePlacementSegmentUnit</code>
 */
class OnePlacementSegmentUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string segment_id = 1;</code>
     */
    private $segment_id = '';
    /**
     * Generated from protobuf field <code>int32 enable = 2;</code>
     */
    private $enable = 0;
    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     */
    private $ecpm_optimization_switch = 0;
    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     */
    private $ecpm = '';
    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 5;</code>
     */
    private $cap_hour_switch = 0;
    /**
     * Generated from protobuf field <code>int32 cap_hour = 6;</code>
     */
    private $cap_hour = 0;
    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 7;</code>
     */
    private $cap_day_switch = 0;
    /**
     * Generated from protobuf field <code>int32 cap_day = 8;</code>
     */
    private $cap_day = 0;
    /**
     * Generated from protobuf field <code>int32 pacing_switch = 9;</code>
     */
    private $pacing_switch = 0;
    /**
     * Generated from protobuf field <code>int32 pacing = 10;</code>
     */
    private $pacing = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $segment_id
     *     @type int $enable
     *     @type int $ecpm_optimization_switch
     *     @type string $ecpm
     *     @type int $cap_hour_switch
     *     @type int $cap_hour
     *     @type int $cap_day_switch
     *     @type int $cap_day
     *     @type int $pacing_switch
     *     @type int $pacing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string segment_id = 1;</code>
     * @return string
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>string segment_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 enable = 2;</code>
     * @return int
     */
    public function getEnable()
    {
        return $this->enable;
    }

    /**
     * Generated from protobuf field <code>int32 enable = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEnable($var)
    {
        GPBUtil::checkInt32($var);
        $this->enable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     * @return int
     */
    public function getEcpmOptimizationSwitch()
    {
        return $this->ecpm_optimization_switch;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEcpmOptimizationSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->ecpm_optimization_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     * @return string
     */
    public function getEcpm()
    {
        return $this->ecpm;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEcpm($var)
    {
        GPBUtil::checkString($var, True);
        $this->ecpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 5;</code>
     * @return int
     */
    public function getCapHourSwitch()
    {
        return $this->cap_hour_switch;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour_switch = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHourSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_hour_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour = 6;</code>
     * @return int
     */
    public function getCapHour()
    {
        return $this->cap_hour;
    }

    /**
     * Generated from protobuf field <code>int32 cap_hour = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCapHour($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_hour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 7;</code>
     * @return int
     */
    public function getCapDaySwitch()
    {
        return $this->cap_day_switch;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day_switch = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDaySwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_day_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day = 8;</code>
     * @return int
     */
    public function getCapDay()
    {
        return $this->cap_day;
    }

    /**
     * Generated from protobuf field <code>int32 cap_day = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCapDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->cap_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacing_switch = 9;</code>
     * @return int
     */
    public function getPacingSwitch()
    {
        return $this->pacing_switch;
    }

    /**
     * Generated from protobuf field <code>int32 pacing_switch = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPacingSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacing_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 10;</code>
     * @return int
     */
    public function getPacing()
    {
        return $this->pacing;
    }

    /**
     * Generated from protobuf field <code>int32 pacing = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPacing($var)
    {
        GPBUtil::checkInt32($var);
        $this->pacing = $var;

        return $this;
    }

}

