<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OnePlacementGroupSegmentData</code>
 */
class OnePlacementGroupSegmentData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit ad_source_list = 1;</code>
     */
    private $ad_source_list;
    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit free_ad_source_list = 2;</code>
     */
    private $free_ad_source_list;
    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segment_data = 3;</code>
     */
    private $segment_data = null;
    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 4;</code>
     */
    private $unit_lists;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $ad_source_list
     *     @type \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $free_ad_source_list
     *     @type \Proto\SegmentGroup $segment_data
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $unit_lists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit ad_source_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdSourceList()
    {
        return $this->ad_source_list;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit ad_source_list = 1;</code>
     * @param \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdSourceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OnePlacementGroupSegmentUnit::class);
        $this->ad_source_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit free_ad_source_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFreeAdSourceList()
    {
        return $this->free_ad_source_list;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroupSegmentUnit free_ad_source_list = 2;</code>
     * @param \Proto\OnePlacementGroupSegmentUnit[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFreeAdSourceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OnePlacementGroupSegmentUnit::class);
        $this->free_ad_source_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segment_data = 3;</code>
     * @return \Proto\SegmentGroup
     */
    public function getSegmentData()
    {
        return $this->segment_data;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentGroup segment_data = 3;</code>
     * @param \Proto\SegmentGroup $var
     * @return $this
     */
    public function setSegmentData($var)
    {
        GPBUtil::checkMessage($var, \Proto\SegmentGroup::class);
        $this->segment_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnitLists()
    {
        return $this->unit_lists;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnitLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->unit_lists = $arr;

        return $this;
    }

}

