<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.oneSegmentRule</code>
 */
class oneSegmentRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int32 rule = 2;</code>
     */
    private $rule = 0;
    /**
     * Generated from protobuf field <code>string rule_content = 3;</code>
     */
    private $rule_content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $rule
     *     @type string $rule_content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rule = 2;</code>
     * @return int
     */
    public function getRule()
    {
        return $this->rule;
    }

    /**
     * Generated from protobuf field <code>int32 rule = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkInt32($var);
        $this->rule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rule_content = 3;</code>
     * @return string
     */
    public function getRuleContent()
    {
        return $this->rule_content;
    }

    /**
     * Generated from protobuf field <code>string rule_content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_content = $var;

        return $this;
    }

}

