<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OneUnit</code>
 */
class OneUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 mediationConnectionId = 1;</code>
     */
    private $mediationConnectionId = 0;
    /**
     * Generated from protobuf field <code>int32 unitId = 2;</code>
     */
    private $unitId = 0;
    /**
     * Generated from protobuf field <code>int32 EcpmOptimizationSwitch = 3;</code>
     */
    private $EcpmOptimizationSwitch = 0;
    /**
     * Generated from protobuf field <code>int32 Type = 4;</code>
     */
    private $Type = 0;
    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     */
    private $createTime = '';
    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     */
    private $updateTime = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mediationConnectionId
     *     @type int $unitId
     *     @type int $EcpmOptimizationSwitch
     *     @type int $Type
     *     @type string $createTime
     *     @type string $updateTime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 mediationConnectionId = 1;</code>
     * @return int
     */
    public function getMediationConnectionId()
    {
        return $this->mediationConnectionId;
    }

    /**
     * Generated from protobuf field <code>int32 mediationConnectionId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMediationConnectionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->mediationConnectionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unitId = 2;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unitId;
    }

    /**
     * Generated from protobuf field <code>int32 unitId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unitId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 EcpmOptimizationSwitch = 3;</code>
     * @return int
     */
    public function getEcpmOptimizationSwitch()
    {
        return $this->EcpmOptimizationSwitch;
    }

    /**
     * Generated from protobuf field <code>int32 EcpmOptimizationSwitch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEcpmOptimizationSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->EcpmOptimizationSwitch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     * Generated from protobuf field <code>string createTime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->createTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     * Generated from protobuf field <code>string updateTime = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->updateTime = $var;

        return $this;
    }

}

