<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlacementTrafficSegment</code>
 */
class PlacementTrafficSegment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 1;</code>
     */
    private $traffic_group_id = 0;
    /**
     * Generated from protobuf field <code>.proto.SegmentOneUnit segment_one_unit = 2;</code>
     */
    private $segment_one_unit = null;
    /**
     * Generated from protobuf field <code>int32 abtype = 3;</code>
     */
    private $abtype = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $traffic_group_id
     *     @type \Proto\SegmentOneUnit $segment_one_unit
     *     @type int $abtype
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 1;</code>
     * @return int
     */
    public function getTrafficGroupId()
    {
        return $this->traffic_group_id;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTrafficGroupId($var)
    {
        GPBUtil::checkInt32($var);
        $this->traffic_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentOneUnit segment_one_unit = 2;</code>
     * @return \Proto\SegmentOneUnit
     */
    public function getSegmentOneUnit()
    {
        return $this->segment_one_unit;
    }

    /**
     * Generated from protobuf field <code>.proto.SegmentOneUnit segment_one_unit = 2;</code>
     * @param \Proto\SegmentOneUnit $var
     * @return $this
     */
    public function setSegmentOneUnit($var)
    {
        GPBUtil::checkMessage($var, \Proto\SegmentOneUnit::class);
        $this->segment_one_unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 abtype = 3;</code>
     * @return int
     */
    public function getAbtype()
    {
        return $this->abtype;
    }

    /**
     * Generated from protobuf field <code>int32 abtype = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAbtype($var)
    {
        GPBUtil::checkInt32($var);
        $this->abtype = $var;

        return $this;
    }

}

