<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlacementEntity</code>
 */
class PlacementEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string uuid = 2;</code>
     */
    private $uuid = '';
    /**
     * Generated from protobuf field <code>uint32 publisher_id = 3;</code>
     */
    private $publisher_id = 0;
    /**
     * Generated from protobuf field <code>uint32 system = 4;</code>
     */
    private $system = 0;
    /**
     * Generated from protobuf field <code>uint32 app_id = 5;</code>
     */
    private $app_id = 0;
    /**
     * Generated from protobuf field <code>string name = 6;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>uint32 format = 7;</code>
     */
    private $format = 0;
    /**
     * Generated from protobuf field <code>int32 status = 8;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>int32 delivery = 9;</code>
     */
    private $delivery = 0;
    /**
     * Generated from protobuf field <code>int32 offer_switch = 10;</code>
     */
    private $offer_switch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $uuid
     *     @type int $publisher_id
     *     @type int $system
     *     @type int $app_id
     *     @type string $name
     *     @type int $format
     *     @type int $status
     *     @type int $delivery
     *     @type int $offer_switch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uuid = 2;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 publisher_id = 3;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Generated from protobuf field <code>uint32 publisher_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkUint32($var);
        $this->publisher_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 system = 4;</code>
     * @return int
     */
    public function getSystem()
    {
        return $this->system;
    }

    /**
     * Generated from protobuf field <code>uint32 system = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSystem($var)
    {
        GPBUtil::checkUint32($var);
        $this->system = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 5;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 format = 7;</code>
     * @return int
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>uint32 format = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkUint32($var);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 delivery = 9;</code>
     * @return int
     */
    public function getDelivery()
    {
        return $this->delivery;
    }

    /**
     * Generated from protobuf field <code>int32 delivery = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setDelivery($var)
    {
        GPBUtil::checkInt32($var);
        $this->delivery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offer_switch = 10;</code>
     * @return int
     */
    public function getOfferSwitch()
    {
        return $this->offer_switch;
    }

    /**
     * Generated from protobuf field <code>int32 offer_switch = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setOfferSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->offer_switch = $var;

        return $this;
    }

}

