<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlacementWaterfallData</code>
 */
class PlacementWaterfallData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_ab_test = 1;</code>
     */
    private $is_ab_test = false;
    /**
     * Generated from protobuf field <code>string placement_id = 2;</code>
     */
    private $placement_id = '';
    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 3;</code>
     */
    private $unit_lists;
    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroup groups = 4;</code>
     */
    private $groups;
    /**
     * Generated from protobuf field <code>int32 placement_offer_switch = 5;</code>
     */
    private $placement_offer_switch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_ab_test
     *     @type string $placement_id
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $unit_lists
     *     @type \Proto\OnePlacementGroup[]|\Google\Protobuf\Internal\RepeatedField $groups
     *     @type int $placement_offer_switch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_ab_test = 1;</code>
     * @return bool
     */
    public function getIsAbTest()
    {
        return $this->is_ab_test;
    }

    /**
     * Generated from protobuf field <code>bool is_ab_test = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAbTest($var)
    {
        GPBUtil::checkBool($var);
        $this->is_ab_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 2;</code>
     * @return string
     */
    public function getPlacementId()
    {
        return $this->placement_id;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->placement_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnitLists()
    {
        return $this->unit_lists;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unit_lists = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnitLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->unit_lists = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroup groups = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.OnePlacementGroup groups = 4;</code>
     * @param \Proto\OnePlacementGroup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OnePlacementGroup::class);
        $this->groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 placement_offer_switch = 5;</code>
     * @return int
     */
    public function getPlacementOfferSwitch()
    {
        return $this->placement_offer_switch;
    }

    /**
     * Generated from protobuf field <code>int32 placement_offer_switch = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPlacementOfferSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->placement_offer_switch = $var;

        return $this;
    }

}

