<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlacementTrafficGroupSegmentUnitOptimization</code>
 */
class PlacementTrafficGroupSegmentUnitOptimization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     */
    private $publisher_id = 0;
    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     */
    private $traffic_group_id = 0;
    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     */
    private $placement_id = '';
    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     */
    private $segment_id = '';
    /**
     * Generated from protobuf field <code>int32 unit_id = 5;</code>
     */
    private $unit_id = 0;
    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 6;</code>
     */
    private $ecpm_optimization_switch = 0;
    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     */
    private $ecpm = '';
    /**
     * Generated from protobuf field <code>int32 admin_id = 8;</code>
     */
    private $admin_id = 0;
    /**
     * Generated from protobuf field <code>string ip = 9;</code>
     */
    private $ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $publisher_id
     *     @type int $traffic_group_id
     *     @type string $placement_id
     *     @type string $segment_id
     *     @type int $unit_id
     *     @type int $ecpm_optimization_switch
     *     @type string $ecpm
     *     @type int $admin_id
     *     @type string $ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisher_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     * @return int
     */
    public function getTrafficGroupId()
    {
        return $this->traffic_group_id;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTrafficGroupId($var)
    {
        GPBUtil::checkInt32($var);
        $this->traffic_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     * @return string
     */
    public function getPlacementId()
    {
        return $this->placement_id;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->placement_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     * @return string
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 5;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 6;</code>
     * @return int
     */
    public function getEcpmOptimizationSwitch()
    {
        return $this->ecpm_optimization_switch;
    }

    /**
     * Generated from protobuf field <code>int32 ecpm_optimization_switch = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEcpmOptimizationSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->ecpm_optimization_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     * @return string
     */
    public function getEcpm()
    {
        return $this->ecpm;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEcpm($var)
    {
        GPBUtil::checkString($var, True);
        $this->ecpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 8;</code>
     * @return int
     */
    public function getAdminId()
    {
        return $this->admin_id;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAdminId($var)
    {
        GPBUtil::checkInt32($var);
        $this->admin_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 9;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

