<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlacementTrafficGroupSegmentConfig</code>
 */
class PlacementTrafficGroupSegmentConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     */
    private $publisher_id = 0;
    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     */
    private $traffic_group_id = 0;
    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     */
    private $placement_id = '';
    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     */
    private $segment_id = '';
    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 5;</code>
     */
    private $parallel_request_number = 0;
    /**
     * Generated from protobuf field <code>repeated string geo_short = 6;</code>
     */
    private $geo_short;
    /**
     * Generated from protobuf field <code>int32 admin_id = 7;</code>
     */
    private $admin_id = 0;
    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     */
    private $ip = '';
    /**
     * Generated from protobuf field <code>int32 offer_switch = 9;</code>
     */
    private $offer_switch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $publisher_id
     *     @type int $traffic_group_id
     *     @type string $placement_id
     *     @type string $segment_id
     *     @type int $parallel_request_number
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $geo_short
     *     @type int $admin_id
     *     @type string $ip
     *     @type int $offer_switch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisher_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     * @return int
     */
    public function getTrafficGroupId()
    {
        return $this->traffic_group_id;
    }

    /**
     * Generated from protobuf field <code>int32 traffic_group_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTrafficGroupId($var)
    {
        GPBUtil::checkInt32($var);
        $this->traffic_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     * @return string
     */
    public function getPlacementId()
    {
        return $this->placement_id;
    }

    /**
     * Generated from protobuf field <code>string placement_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->placement_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     * @return string
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>string segment_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 5;</code>
     * @return int
     */
    public function getParallelRequestNumber()
    {
        return $this->parallel_request_number;
    }

    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setParallelRequestNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->parallel_request_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string geo_short = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeoShort()
    {
        return $this->geo_short;
    }

    /**
     * Generated from protobuf field <code>repeated string geo_short = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeoShort($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->geo_short = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 7;</code>
     * @return int
     */
    public function getAdminId()
    {
        return $this->admin_id;
    }

    /**
     * Generated from protobuf field <code>int32 admin_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAdminId($var)
    {
        GPBUtil::checkInt32($var);
        $this->admin_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offer_switch = 9;</code>
     * @return int
     */
    public function getOfferSwitch()
    {
        return $this->offer_switch;
    }

    /**
     * Generated from protobuf field <code>int32 offer_switch = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOfferSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->offer_switch = $var;

        return $this;
    }

}

