<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\PlatformUnitList\PlatformUnitEntity instead.
     * @deprecated
     */
    class PlatformUnitList_PlatformUnitEntity {}
}
class_exists(PlatformUnitList\PlatformUnitEntity::class);
@trigger_error('Proto\PlatformUnitList_PlatformUnitEntity is deprecated and will be removed in the next major release. Use Proto\PlatformUnitList\PlatformUnitEntity instead', E_USER_DEPRECATED);

