<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PlatformUnitList</code>
 */
class PlatformUnitList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.PlatformUnitList.PlatformUnitEntity pue = 1;</code>
     */
    private $pue;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PlatformUnitList\PlatformUnitEntity[]|\Google\Protobuf\Internal\RepeatedField $pue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PlatformUnitList.PlatformUnitEntity pue = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPue()
    {
        return $this->pue;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PlatformUnitList.PlatformUnitEntity pue = 1;</code>
     * @param \Proto\PlatformUnitList\PlatformUnitEntity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PlatformUnitList\PlatformUnitEntity::class);
        $this->pue = $arr;

        return $this;
    }

}

