<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openapi.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherPlacementList</code>
 */
class PublisherPlacementList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string AppUuids = 1;</code>
     */
    private $AppUuids;
    /**
     * Generated from protobuf field <code>repeated string placementIds = 2;</code>
     */
    private $placementIds;
    /**
     * Generated from protobuf field <code>int32 publisherId = 3;</code>
     */
    private $publisherId = 0;
    /**
     * Generated from protobuf field <code>int32 start = 4;</code>
     */
    private $start = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     */
    private $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $AppUuids
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $placementIds
     *     @type int $publisherId
     *     @type int $start
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string AppUuids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppUuids()
    {
        return $this->AppUuids;
    }

    /**
     * Generated from protobuf field <code>repeated string AppUuids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppUuids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->AppUuids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string placementIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlacementIds()
    {
        return $this->placementIds;
    }

    /**
     * Generated from protobuf field <code>repeated string placementIds = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlacementIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->placementIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 3;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisherId;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 start = 4;</code>
     * @return int
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>int32 start = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkInt32($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

