<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openapi.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherOpenApiResponse</code>
 */
class PublisherOpenApiResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string publisherKey = 1;</code>
     */
    private $publisherKey = '';
    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     */
    private $publisherId = 0;
    /**
     * Generated from protobuf field <code>int32 upApiPermission = 3;</code>
     */
    private $upApiPermission = 0;
    /**
     * Generated from protobuf field <code>int32 upDevicePermission = 4;</code>
     */
    private $upDevicePermission = 0;
    /**
     * Generated from protobuf field <code>int32 publisherMode = 5;</code>
     */
    private $publisherMode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $publisherKey
     *     @type int $publisherId
     *     @type int $upApiPermission
     *     @type int $upDevicePermission
     *     @type int $publisherMode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string publisherKey = 1;</code>
     * @return string
     */
    public function getPublisherKey()
    {
        return $this->publisherKey;
    }

    /**
     * Generated from protobuf field <code>string publisherKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisherKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisherId;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 upApiPermission = 3;</code>
     * @return int
     */
    public function getUpApiPermission()
    {
        return $this->upApiPermission;
    }

    /**
     * Generated from protobuf field <code>int32 upApiPermission = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUpApiPermission($var)
    {
        GPBUtil::checkInt32($var);
        $this->upApiPermission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 upDevicePermission = 4;</code>
     * @return int
     */
    public function getUpDevicePermission()
    {
        return $this->upDevicePermission;
    }

    /**
     * Generated from protobuf field <code>int32 upDevicePermission = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUpDevicePermission($var)
    {
        GPBUtil::checkInt32($var);
        $this->upDevicePermission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherMode = 5;</code>
     * @return int
     */
    public function getPublisherMode()
    {
        return $this->publisherMode;
    }

    /**
     * Generated from protobuf field <code>int32 publisherMode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherMode($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherMode = $var;

        return $this;
    }

}

