<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openapi.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherOnePlacementEntity</code>
 */
class PublisherOnePlacementEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string placementName = 1;</code>
     */
    private $placementName = '';
    /**
     * Generated from protobuf field <code>int32 placementAdFormat = 2;</code>
     */
    private $placementAdFormat = 0;
    /**
     * Generated from protobuf field <code>string placementId = 3;</code>
     */
    private $placementId = '';
    /**
     * Generated from protobuf field <code>int32 appId = 4;</code>
     */
    private $appId = 0;
    /**
     * Generated from protobuf field <code>string appUuId = 5;</code>
     */
    private $appUuId = '';
    /**
     * Generated from protobuf field <code>string appName = 6;</code>
     */
    private $appName = '';
    /**
     * Generated from protobuf field <code>int32 appPlatform = 7;</code>
     */
    private $appPlatform = 0;
    /**
     * Generated from protobuf field <code>int32 publisherId = 8;</code>
     */
    private $publisherId = 0;
    /**
     * Generated from protobuf field <code>string msg = 9;</code>
     */
    private $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $placementName
     *     @type int $placementAdFormat
     *     @type string $placementId
     *     @type int $appId
     *     @type string $appUuId
     *     @type string $appName
     *     @type int $appPlatform
     *     @type int $publisherId
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string placementName = 1;</code>
     * @return string
     */
    public function getPlacementName()
    {
        return $this->placementName;
    }

    /**
     * Generated from protobuf field <code>string placementName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementName($var)
    {
        GPBUtil::checkString($var, True);
        $this->placementName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 placementAdFormat = 2;</code>
     * @return int
     */
    public function getPlacementAdFormat()
    {
        return $this->placementAdFormat;
    }

    /**
     * Generated from protobuf field <code>int32 placementAdFormat = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPlacementAdFormat($var)
    {
        GPBUtil::checkInt32($var);
        $this->placementAdFormat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placementId = 3;</code>
     * @return string
     */
    public function getPlacementId()
    {
        return $this->placementId;
    }

    /**
     * Generated from protobuf field <code>string placementId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->placementId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 appId = 4;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>int32 appId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkInt32($var);
        $this->appId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appUuId = 5;</code>
     * @return string
     */
    public function getAppUuId()
    {
        return $this->appUuId;
    }

    /**
     * Generated from protobuf field <code>string appUuId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppUuId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appUuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appName = 6;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->appName;
    }

    /**
     * Generated from protobuf field <code>string appName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->appName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 appPlatform = 7;</code>
     * @return int
     */
    public function getAppPlatform()
    {
        return $this->appPlatform;
    }

    /**
     * Generated from protobuf field <code>int32 appPlatform = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAppPlatform($var)
    {
        GPBUtil::checkInt32($var);
        $this->appPlatform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 8;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisherId;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 9;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

