<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openapi.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherOpenApiEntity</code>
 */
class PublisherOpenApiEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string publisher_key = 1;</code>
     */
    private $publisher_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $publisher_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string publisher_key = 1;</code>
     * @return string
     */
    public function getPublisherKey()
    {
        return $this->publisher_key;
    }

    /**
     * Generated from protobuf field <code>string publisher_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_key = $var;

        return $this;
    }

}

