<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openapi.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherPlacementEntitys</code>
 */
class PublisherPlacementEntitys extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.PublisherOnePlacementEntity placementEntitys = 1;</code>
     */
    private $placementEntitys;
    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     */
    private $publisherId = 0;
    /**
     * Generated from protobuf field <code>string appUuid = 3;</code>
     */
    private $appUuid = '';
    /**
     * Generated from protobuf field <code>int32 publisherMode = 4;</code>
     */
    private $publisherMode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PublisherOnePlacementEntity[]|\Google\Protobuf\Internal\RepeatedField $placementEntitys
     *     @type int $publisherId
     *     @type string $appUuid
     *     @type int $publisherMode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PublisherOnePlacementEntity placementEntitys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlacementEntitys()
    {
        return $this->placementEntitys;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PublisherOnePlacementEntity placementEntitys = 1;</code>
     * @param \Proto\PublisherOnePlacementEntity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlacementEntitys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PublisherOnePlacementEntity::class);
        $this->placementEntitys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisherId;
    }

    /**
     * Generated from protobuf field <code>int32 publisherId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appUuid = 3;</code>
     * @return string
     */
    public function getAppUuid()
    {
        return $this->appUuid;
    }

    /**
     * Generated from protobuf field <code>string appUuid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->appUuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisherMode = 4;</code>
     * @return int
     */
    public function getPublisherMode()
    {
        return $this->publisherMode;
    }

    /**
     * Generated from protobuf field <code>int32 publisherMode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherMode($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisherMode = $var;

        return $this;
    }

}

