<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PublisherEntityList</code>
 */
class PublisherEntityList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.PublisherEntity publishers = 1;</code>
     */
    private $publishers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PublisherEntity[]|\Google\Protobuf\Internal\RepeatedField $publishers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PublisherEntity publishers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublishers()
    {
        return $this->publishers;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PublisherEntity publishers = 1;</code>
     * @param \Proto\PublisherEntity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublishers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PublisherEntity::class);
        $this->publishers = $arr;

        return $this;
    }

}

