<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\SegmentUnitList\SegmentUnitEntity instead.
     * @deprecated
     */
    class SegmentUnitList_SegmentUnitEntity {}
}
class_exists(SegmentUnitList\SegmentUnitEntity::class);
@trigger_error('Proto\SegmentUnitList_SegmentUnitEntity is deprecated and will be removed in the next major release. Use Proto\SegmentUnitList\SegmentUnitEntity instead', E_USER_DEPRECATED);

