<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SegmentGroup</code>
 */
class SegmentGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 1;</code>
     */
    private $parallel_request_number = 0;
    /**
     * Generated from protobuf field <code>string create_time = 2;</code>
     */
    private $create_time = '';
    /**
     * Generated from protobuf field <code>string update_time = 3;</code>
     */
    private $update_time = '';
    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 4;</code>
     */
    private $one_segment = null;
    /**
     * Generated from protobuf field <code>repeated .proto.oneSegmentRule rules = 5;</code>
     */
    private $rules;
    /**
     * Generated from protobuf field <code>int32 segment_rank = 6;</code>
     */
    private $segment_rank = 0;
    /**
     * Generated from protobuf field <code>int32 segment_offer_switch = 7;</code>
     */
    private $segment_offer_switch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $parallel_request_number
     *     @type string $create_time
     *     @type string $update_time
     *     @type \Proto\OneSegment $one_segment
     *     @type \Proto\oneSegmentRule[]|\Google\Protobuf\Internal\RepeatedField $rules
     *     @type int $segment_rank
     *     @type int $segment_offer_switch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 1;</code>
     * @return int
     */
    public function getParallelRequestNumber()
    {
        return $this->parallel_request_number;
    }

    /**
     * Generated from protobuf field <code>int32 parallel_request_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setParallelRequestNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->parallel_request_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string create_time = 2;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>string create_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string update_time = 3;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>string update_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 4;</code>
     * @return \Proto\OneSegment
     */
    public function getOneSegment()
    {
        return $this->one_segment;
    }

    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 4;</code>
     * @param \Proto\OneSegment $var
     * @return $this
     */
    public function setOneSegment($var)
    {
        GPBUtil::checkMessage($var, \Proto\OneSegment::class);
        $this->one_segment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.oneSegmentRule rules = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.oneSegmentRule rules = 5;</code>
     * @param \Proto\oneSegmentRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\oneSegmentRule::class);
        $this->rules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 segment_rank = 6;</code>
     * @return int
     */
    public function getSegmentRank()
    {
        return $this->segment_rank;
    }

    /**
     * Generated from protobuf field <code>int32 segment_rank = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSegmentRank($var)
    {
        GPBUtil::checkInt32($var);
        $this->segment_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 segment_offer_switch = 7;</code>
     * @return int
     */
    public function getSegmentOfferSwitch()
    {
        return $this->segment_offer_switch;
    }

    /**
     * Generated from protobuf field <code>int32 segment_offer_switch = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSegmentOfferSwitch($var)
    {
        GPBUtil::checkInt32($var);
        $this->segment_offer_switch = $var;

        return $this;
    }

}

