<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SegmentOneUnit</code>
 */
class SegmentOneUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 1;</code>
     */
    private $one_segment = null;
    /**
     * Generated from protobuf field <code>.proto.OnePlacementGroupSegmentUnit one_unit = 2;</code>
     */
    private $one_unit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\OneSegment $one_segment
     *     @type \Proto\OnePlacementGroupSegmentUnit $one_unit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 1;</code>
     * @return \Proto\OneSegment
     */
    public function getOneSegment()
    {
        return $this->one_segment;
    }

    /**
     * Generated from protobuf field <code>.proto.OneSegment one_segment = 1;</code>
     * @param \Proto\OneSegment $var
     * @return $this
     */
    public function setOneSegment($var)
    {
        GPBUtil::checkMessage($var, \Proto\OneSegment::class);
        $this->one_segment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.OnePlacementGroupSegmentUnit one_unit = 2;</code>
     * @return \Proto\OnePlacementGroupSegmentUnit
     */
    public function getOneUnit()
    {
        return $this->one_unit;
    }

    /**
     * Generated from protobuf field <code>.proto.OnePlacementGroupSegmentUnit one_unit = 2;</code>
     * @param \Proto\OnePlacementGroupSegmentUnit $var
     * @return $this
     */
    public function setOneUnit($var)
    {
        GPBUtil::checkMessage($var, \Proto\OnePlacementGroupSegmentUnit::class);
        $this->one_unit = $var;

        return $this;
    }

}

