<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SegmentUnitList</code>
 */
class SegmentUnitList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.SegmentUnitList.SegmentUnitEntity sue = 1;</code>
     */
    private $sue;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\SegmentUnitList\SegmentUnitEntity[]|\Google\Protobuf\Internal\RepeatedField $sue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.SegmentUnitList.SegmentUnitEntity sue = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSue()
    {
        return $this->sue;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.SegmentUnitList.SegmentUnitEntity sue = 1;</code>
     * @param \Proto\SegmentUnitList\SegmentUnitEntity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\SegmentUnitList\SegmentUnitEntity::class);
        $this->sue = $arr;

        return $this;
    }

}

