<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitUpInfoList</code>
 */
class UnitUpInfoList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.UnitUpInfoList.UnitUpInfo units = 1;</code>
     */
    private $units;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\UnitUpInfoList\UnitUpInfo[]|\Google\Protobuf\Internal\RepeatedField $units
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UnitUpInfoList.UnitUpInfo units = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnits()
    {
        return $this->units;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UnitUpInfoList.UnitUpInfo units = 1;</code>
     * @param \Proto\UnitUpInfoList\UnitUpInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\UnitUpInfoList\UnitUpInfo::class);
        $this->units = $arr;

        return $this;
    }

}

