<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitRemote</code>
 */
class UnitRemote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string remote_unique = 1;</code>
     */
    private $remote_unique = '';
    /**
     * Generated from protobuf field <code>int32 publisher_id = 2;</code>
     */
    private $publisher_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $remote_unique
     *     @type int $publisher_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string remote_unique = 1;</code>
     * @return string
     */
    public function getRemoteUnique()
    {
        return $this->remote_unique;
    }

    /**
     * Generated from protobuf field <code>string remote_unique = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteUnique($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_unique = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 2;</code>
     * @return int
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Generated from protobuf field <code>int32 publisher_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkInt32($var);
        $this->publisher_id = $var;

        return $this;
    }

}

