<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitSegmentPlacementTrafficGroups</code>
 */
class UnitSegmentPlacementTrafficGroups extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.UnitSegmentPlacementTrafficGroup unit_optimizations = 1;</code>
     */
    private $unit_optimizations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\UnitSegmentPlacementTrafficGroup[]|\Google\Protobuf\Internal\RepeatedField $unit_optimizations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UnitSegmentPlacementTrafficGroup unit_optimizations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnitOptimizations()
    {
        return $this->unit_optimizations;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UnitSegmentPlacementTrafficGroup unit_optimizations = 1;</code>
     * @param \Proto\UnitSegmentPlacementTrafficGroup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnitOptimizations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\UnitSegmentPlacementTrafficGroup::class);
        $this->unit_optimizations = $arr;

        return $this;
    }

}

