<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitEcpmOptimizationLog</code>
 */
class UnitEcpmOptimizationLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     */
    private $unit_id = 0;
    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     */
    private $geo_short = '';
    /**
     * Generated from protobuf field <code>int32 impressions = 3;</code>
     */
    private $impressions = 0;
    /**
     * Generated from protobuf field <code>int32 date_time = 4;</code>
     */
    private $date_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $unit_id
     *     @type string $geo_short
     *     @type int $impressions
     *     @type int $date_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     * @return string
     */
    public function getGeoShort()
    {
        return $this->geo_short;
    }

    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGeoShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->geo_short = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 impressions = 3;</code>
     * @return int
     */
    public function getImpressions()
    {
        return $this->impressions;
    }

    /**
     * Generated from protobuf field <code>int32 impressions = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setImpressions($var)
    {
        GPBUtil::checkInt32($var);
        $this->impressions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 date_time = 4;</code>
     * @return int
     */
    public function getDateTime()
    {
        return $this->date_time;
    }

    /**
     * Generated from protobuf field <code>int32 date_time = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDateTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->date_time = $var;

        return $this;
    }

}

