<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitEntity</code>
 */
class UnitEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int32 placement_id = 2;</code>
     */
    private $placement_id = 0;
    /**
     * Generated from protobuf field <code>int32 network_id = 3;</code>
     */
    private $network_id = 0;
    /**
     * Generated from protobuf field <code>string network_name = 4;</code>
     */
    private $network_name = '';
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     */
    private $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $placement_id
     *     @type int $network_id
     *     @type string $network_name
     *     @type string $name
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 placement_id = 2;</code>
     * @return int
     */
    public function getPlacementId()
    {
        return $this->placement_id;
    }

    /**
     * Generated from protobuf field <code>int32 placement_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPlacementId($var)
    {
        GPBUtil::checkInt32($var);
        $this->placement_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 network_id = 3;</code>
     * @return int
     */
    public function getNetworkId()
    {
        return $this->network_id;
    }

    /**
     * Generated from protobuf field <code>int32 network_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNetworkId($var)
    {
        GPBUtil::checkInt32($var);
        $this->network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network_name = 4;</code>
     * @return string
     */
    public function getNetworkName()
    {
        return $this->network_name;
    }

    /**
     * Generated from protobuf field <code>string network_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNetworkName($var)
    {
        GPBUtil::checkString($var, True);
        $this->network_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

