<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UnitUpInfoList\UnitUpInfo instead.
     * @deprecated
     */
    class UnitUpInfoList_UnitUpInfo {}
}
class_exists(UnitUpInfoList\UnitUpInfo::class);
@trigger_error('Proto\UnitUpInfoList_UnitUpInfo is deprecated and will be removed in the next major release. Use Proto\UnitUpInfoList\UnitUpInfo instead', E_USER_DEPRECATED);

