<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meta.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UnitEcpmOptimization</code>
 */
class UnitEcpmOptimization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     */
    private $unit_id = 0;
    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     */
    private $geo_short = '';
    /**
     * Generated from protobuf field <code>int32 optimization_status = 3;</code>
     */
    private $optimization_status = 0;
    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     */
    private $ecpm = '';
    /**
     * Generated from protobuf field <code>int32 impressions = 5;</code>
     */
    private $impressions = 0;
    /**
     * Generated from protobuf field <code>float revenues = 6;</code>
     */
    private $revenues = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $unit_id
     *     @type string $geo_short
     *     @type int $optimization_status
     *     @type string $ecpm
     *     @type int $impressions
     *     @type float $revenues
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     * @return int
     */
    public function getUnitId()
    {
        return $this->unit_id;
    }

    /**
     * Generated from protobuf field <code>int32 unit_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitId($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     * @return string
     */
    public function getGeoShort()
    {
        return $this->geo_short;
    }

    /**
     * Generated from protobuf field <code>string geo_short = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGeoShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->geo_short = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 optimization_status = 3;</code>
     * @return int
     */
    public function getOptimizationStatus()
    {
        return $this->optimization_status;
    }

    /**
     * Generated from protobuf field <code>int32 optimization_status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOptimizationStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->optimization_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     * @return string
     */
    public function getEcpm()
    {
        return $this->ecpm;
    }

    /**
     * Generated from protobuf field <code>string ecpm = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEcpm($var)
    {
        GPBUtil::checkString($var, True);
        $this->ecpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 impressions = 5;</code>
     * @return int
     */
    public function getImpressions()
    {
        return $this->impressions;
    }

    /**
     * Generated from protobuf field <code>int32 impressions = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setImpressions($var)
    {
        GPBUtil::checkInt32($var);
        $this->impressions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float revenues = 6;</code>
     * @return float
     */
    public function getRevenues()
    {
        return $this->revenues;
    }

    /**
     * Generated from protobuf field <code>float revenues = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setRevenues($var)
    {
        GPBUtil::checkFloat($var);
        $this->revenues = $var;

        return $this;
    }

}

