<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/offer.proto

namespace GPBMetadata\Proto;

class Offer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6d0a1170726f746f2f6f666665722e70726f746f120570726f746f2249" .
            "0a0f4f666665725175657565506172616d12140a0c706c6163656d656e74" .
            "5f696418012001280512100a086f666665725f6964180220012805120e0a" .
            "06737461747573180320012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

