<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/quque.proto

namespace GPBMetadata\Proto;

class Quque
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4d0a1170726f746f2f71757175652e70726f746f120570726f746f2229" .
            "0a0d5371735175657565506172616d120c0a047479706518012001280512" .
            "0a0a026964180220012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

